name: Run tests on any Push event

on:
  push:
    branches:
      - '*'

jobs:
  LintsBlack:
    runs-on: ubuntu-latest
    name: Black
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./api"

  LintsFlake8:
    runs-on: ubuntu-latest
    name: Flake8
    steps:
      - uses: actions/checkout@v3
      - uses: py-actions/flake8@v2
        with:
          path: "./api"
          args: "--statistics --count --ignore E501"

  LintsIsort:
    runs-on: ubuntu-latest
    name: Isort
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install isort
        run: pip install isort
      - name: Run isort
        run: isort --profile=black --check-only ./api

  LintsMyPy:
    runs-on: ubuntu-latest
    name: MyPy
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run MyPy
        run: |
          mypy --config-file mypy.ini \
          --show-error-codes \
          --no-error-summary \
          api/

  Tests:
    runs-on: ubuntu-latest
    needs: [LintsBlack, LintsFlake8, LintsIsort, LintsMyPy]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run Docker Compose
        working-directory: ./db-test
        run: docker compose -f docker-compose.yaml up -d

      - name: Wait for containers
        run: sleep 10

      - name: Check running containers
        run: docker ps -a

      - name: View Docker logs
        working-directory: ./db-test
        run: docker compose logs

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'

      - name: Install requirements
        working-directory: ./api
        run: |
          pip install -r requirements.txt
          pip install coverage pytest

      - name: Run tests
        run: coverage run -m pytest tests/test_api.py

      - name: Generate coverage report
        run: coverage report

      - name: Stop containers
        if: always()
        working-directory: ./db-test
        run: docker compose down